appolo_web_service:
    resource: "@AppoloWebServiceBundle/Controller/"
    type:     annotation
    prefix:   /

appolo_back_office:
    resource: "@AppoloBackOfficeBundle/Controller/"
    type:     annotation
    prefix:   /admin

appolo_front_borne:
    resource: "@AppoloFrontBorneBundle/Controller/"
    type:     annotation
    prefix:   /borne

appolo_front_vitrine:
    resource: "@AppoloFrontVitrineBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: AppoloBackOfficeBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

inscription:
    pattern:   /inscription
    defaults:  { _controller: AppoloBackOfficeBundle:Security:inscription }

    
    